FROM node:9.6.1



ENV PATH $PATH:/app/node_modules/.bin

RUN mkdir /app

WORKDIR /app

COPY ./package.json .

RUN npm install

COPY . .

RUN npm run build:dev

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "serve" ]