FROM node:9.6.1

LABEL MAINTAINER="<web@freshworks.io>"

ENV PATH $PATH:/usr/src/app/node_modules/.bin

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies
RUN npm install

EXPOSE 3000

CMD [ "npm", "run", "start" ]
