// Network request reducers
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_GOOGLE_CODE = 'REQUEST_GOOGLE_CODE';
export const REQUEST_GOOGLE_ID_TOKEN = 'REQUEST_GOOGLE_ID_TOKEN';
export const REQUEST_GOOGLE_REVOKE = 'REQUEST_GOOGLE_REVOKE';
export const REQUEST_GOOGLE_TOKEN_CHECK = 'REQUEST_GOOGLE_TOKEN_CHECK';
export const REQUEST_GOOGLE_USERNAME = 'REQUEST_GOOGLE_USERNAME';

export const REQUEST_LOCATIONS_GET = 'REQUEST_LOCATIONS_GET';
export const REQUEST_LOCATIONS_SET = 'REQUEST_LOCATIONS_SET';

export const REQUEST_REVIEWS_GET = 'REQUEST_REVIEWS_GET';
export const REQUEST_REVIEWS_POLL = 'REQUEST_REVIEWS_POLL';
export const REQUEST_LOCATION_REVIEWS_GET = 'REQUEST_LOCATION_REVIEWS_GET';
export const REQUEST_REVIEWS_REPLY = 'REQUEST_REVIEWS_REPLY';

export const REQUEST_QUESTIONS_GET = 'REQUEST_QUESTIONS_GET';
export const REQUEST_QUESTIONS_POLL = 'REQUEST_QUESTIONS_POLL';
export const REQUEST_LOCATIONS_QUESTIONS_GET = 'REQUEST_LOCATIONS_QUESTIONS_GET';
export const REQUEST_QUESTIONS_REPLY = 'REQUEST_QUESTIONS_REPLY';

export const REQUEST_POSTS_GET = 'REQUEST_POSTS_GET';
export const REQUEST_POSTS_POLL = 'REQUEST_POSTS_POLL';
export const REQUEST_POSTS_GET_MORE = 'REQUEST_POSTS_GET_MORE';

export const REQUEST_NOTIFICATIONS_GET = 'REQUEST_NOTIFICATIONS_GET';

export const REQUEST_ADMIN_LOGIN = 'REQUEST_ADMIN_LOGIN';
export const REQUEST_ANALYTICS_GET = 'REQUEST_ANALYTICS_GET';
export const REQUEST_NOTIFICATIONS_POST = 'REQUEST_NOTIFICATIONS_POST';
export const REQUEST_ERROR_LOGS_GET = 'REQUEST_ERROR_LOGS_GET';

// Data storage reducers
export const DATA_JWT = 'DATA_JWT';
export const DATA_LOCATIONS = 'DATA_LOCATIONS';
export const DATA_STREAM = 'DATA_STREAM';
export const DATA_PID = 'DATA_PID';
export const DATA_REVIEWS = 'DATA_REVIEWS';
export const DATA_QUESTIONS = 'DATA_QUESTIONS';
export const DATA_POSTS = 'DATA_POSTS';
export const DATA_USERNAME = 'DATA_USERNAME';
export const DATA_NOTIFICATION = 'DATA_NOTIFICATION';
export const DATA_ADMIN_JWT = 'DATA_ADMIN_JWT';
export const DATA_ANALYTICS = 'DATA_ANALYTICS';
export const DATA_ERROR_LOGS = 'DATA_ERROR_LOGS';

// Toast reducer
export const TOAST = 'TOAST';
